Repository x-atlas-consortia/ubkg-api, pull requests merged in 2024-08, with the labels that each got.

#142 Flask v3x
  pyproject.toml
  src/ubkg_api/requirements.txt
Labels: P

#143 New endpoints for codes and concepts paths
  dd-api-spec.yaml
  src/ubkg_api/common_routes/codes/codes_controller.py
  src/ubkg_api/common_routes/common_neo4j_logic.py
  src/ubkg_api/common_routes/concepts/concepts_controller.py
  src/ubkg_api/cypher/code_code_id_terms.cypher
  src/ubkg_api/cypher/concepts_subgraph_sequential.cypher
  tests/test_dd_api.sh
  tests/test_ubkg_api.sh
  ubkg-api-spec.yaml
Labels: enhancement

#147 Fix to test_ubkg_api.sh for concepts/...subgraph/sequential
  tests/test_ubkg_api.sh
Labels: bug
